name: dr_shahin_uk
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  # firebase_storage: ^13.0.0   # âŒ remove if not needed
  file_picker: ^10.3.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  http: ^1.2.2
  cloudinary_flutter: ^0.9.0
  cloudinary_sdk: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
